import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/header'
import Main from './main'
import { ReactElement } from 'react'

export default function Home(): ReactElement {
     return (
          <div className={styles.container}>
               <Head>
                    <title>Ch Faraz Ahmed</title>
                    <meta
                         name="description"
                         content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
               </Head>

               <Header />
               <Main />
          </div>
     )
}
